#' Expression matrix for H. sapiens
#'
#' This is an example of bulk RNA-Seq dataset with normalized gene counts of 12
#' samples of human embryonic stem cells (hESC h9) differentiated to forebrain
#' and motor neurons. RNA was collected at different time points (day 0, 10, 17
#' and 35) and half of the samples underwent the knockdown of ADAR1.
#' The dataset is publicly available with the accession number GSE56152 on GEO
#' (Chen et al, 2015, Cell Res).
#'
#' @docType data
#'
#' @usage data(matrix)

"matrix"

#' Example expression data for H. sapiens
#'
#' This is an example of bulk RNA-Seq dataset with normalized gene counts of 12
#' samples of human embryonic stem cells (hESC h9) differentiated to forebrain
#' and motor neurons. RNA was collected at different time points (day 0, 10, 17
#' and 35) and half of the samples underwent the knockdown of ADAR1.
#' The dataset is publicly available with the accession number GSE56152 on GEO
#' (Chen et al, 2015, Cell Res).
#' After the normalization, the matrix was filtered to keep only 100 genes,
#' included those of interest (i.e. ADAR and ADARB1).
#' This dataset should be used only with example purpose.
#'
#' @docType data
#'
#' @usage data(example_matrix)

"example_matrix"

#' Example expression data for M. musculus
#'
#' This is an example of bulk RNA-Seq dataset generated by the union of two
#' datasets of mouse neurons and brains, publicly available on GEO with the
#' accession numbers GSE126629 (Sapiro, 2020, Cell Rep) and GSE132214 (Chalk,
#' 2019, Genome Biol). The first dataset consists of WT samples and samples with
#' Adar1, Adar2 and Zfr KD of mouse primary neurons; the second is composed of
#' three samples with Adar2 KO of mouse brains. After the normalization, the
#' matrix was filtered to keep only 100 genes, included those of interest (i.e.
#' Adar and Adarb1).
#' This dataset should be used only with example purpose.
#'
#' @docType data
#'
#' @usage data(example_matrix_Mm)

"example_matrix_Mm"

#' Example gene list for H.sapiens
#'
#' List of genes generated with example purposes to show the functionalities of
#' the function \code{\link[ADARcas]{yourSignature}}.
#'
#' @docType data
#'
#' @usage data(example_genes)

"example_genes"

#' Example network for H. sapiens
#'
#' This is an example of gene regulatory network reconstructed with the R
#' package \pkg{parmigene} to estimate the mutual information, and then by using
#' the additive model of ARACNe (Margolin et al, 2006, BMC Bioinformatics) to
#' obtain a square-weighted adjacency matrix. This network was obtained from the
#' gene expression matrix of the dataset with GEO accession number GSE56152.
#' Then, with example purpose, it was filtered to keep only 50 genes, included
#' those of interest (i.e. ADAR and ADARB1).
#'
#' @docType data
#'
#' @usage data(example_network)

"example_network"

#' Example SingleCellExperiment
#'
#' This is an example of a SingleCellExperiment created to test package
#' functions with the package \pkg{splatter}.
#'
#' @docType data
#'
#' @usage data(example_sce)

"example_sce"
